Repository Code-Poets/sheetstorm, pull requests merged in 2019-09, with the labels that each got.

#530 Bugfix remove CustomUser model fields from admin panel
  users/admin.py
Labels: bug

#521 Chore add headers that improve security in nginx
  sheetstorm-deployment/consts.yml
  sheetstorm-deployment/roles/configure_nginx/templates/maintenance-remote.j2
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
Labels: security

#529 Update release notes for `v0.9.0` tag
  RELEASE-NOTES.md
Labels: chore

#534 Add separate admin endpoint with whitelist of ip addresses
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
Labels: feature, priority medium, security

#532 Add additional sources to csp configuration header
  sheetstorm-deployment/consts.yml
  sheetstorm-deployment/roles/configure_nginx/templates/maintenance-remote.j2
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
Labels: chore, deployment, priority high

#536 Bugfix hide create project for managers
  managers/templates/managers/projects_list.html
Labels: bug, priority high
