Repository Code-Poets/sheetstorm, pull requests merged in 2019-08, with the labels that each got.

#470 Bugfix failing tests in master
  employees/tests/test_views.py
  sheetstorm/settings/base.py
Labels: bug

#467 Bugfix modify template to preserve user's email in case of errors
  users/templates/registration/login.html
  users/templates/signup.html
Labels: bug

#473 Bugfix none displayed in login form
  users/templates/registration/login.html
  users/templates/signup.html
Labels: bug, priority high

#468 Feature add script and cron job that automatically upload postgresql backup to the google cloud storage
  sheetstorm-deployment/configure-sheetstorm-server.yml
  sheetstorm-deployment/create-compute-instance-for-sheetstorm.yml
  sheetstorm-deployment/templates/upload-postgresql-backup-to-gcloud-bucket.sh.j2
Labels: deployment, feature, security

#471 Fix navigation form (in case of malformed date)
  employees/tests/test_unit_custom_mixins.py
  employees/views.py
Labels: bug

#459 Chore update release notes for v0.8.0 tag
  RELEASE-NOTES.md
Labels: chore

#479 Chore remove daily hours from export
  employees/common/constants.py
  employees/common/exports.py
  employees/tests/test_unit_export_data.py
Labels: chore, priority high

#481 Add top border to separate days in excel reports
  employees/common/exports.py
Labels: feature, priority medium

#472 Bugfix managers field in project admin form
  managers/forms.py
  managers/tests/test_views.py
  managers/views.py
  utils/tests/test_access_permissions.py
Labels: bug, priority low

#486 Bugfix incorrect display of reports
  employees/static/employees/style.css
  employees/templates/employees/author_report_list.html
  employees/templates/employees/report_list.html
Labels: bug, priority high

#500 Bugfix disable `cyclic-import` in pylintrc config
  pylintrc
Labels: bug

#503 Bugfix remove task activity from project
  managers/templates/managers/project_task_activities.html
Labels: bug, priority high

#505 Bugfix stop_date and suspended field in project
  managers/models.py
  managers/tests/test_unit_project_signals.py
Labels: bug, priority medium
