Repository Code-Poets/sheetstorm, pull requests merged in 2019-04, with the labels that each got.

#37 Feature support markdown in report description
  employees/models.py
  employees/templates/employees/report_list.html
  requirements.lock
  requirements.txt
  sheetstorm/settings/base.py
Labels: feature

#107 Remove unused users fixtures file
  users/fixtures/initial_users_data.yaml
Labels: bug

#113 Add `.idea/` dir to .gitignore
  .gitignore
Labels: chore

#114 Fix django warnings about renamed `psycopg2`
  requirements.lock
Labels: chore

#127 Move javascript related imports in base.html before block content
  users/templates/base.html
Labels: bug

#128 Add STATIC_ROOT to base settings
  sheetstorm/settings/base.py
Labels: bug

#102 Chore create release notes 0.1.0
  RELEASE-NOTES.md
Labels: chore

#146 Add favicon.ico to base.html
  users/static/images/favicon.ico
  users/templates/base.html
Labels: chore

#158 Change pull request number to URL
  RELEASE-NOTES.md
Labels: bug

#162 Add SheetStorm static files to gitignore
  .gitignore
Labels: chore
