Repository Code-Poets/sheetstorm, pull requests merged in 2019-07, with the labels that each got.

#377 Fix for on report editing, the task activity is set to default
  employees/forms.py
  employees/tests/test_views.py
Labels: bug

#373 Feature add automatically creating and mounting an additional disk for postgression backup purposes
  sheetstorm-deployment/create-compute-instance-for-sheetstorm.yml
  sheetstorm-deployment/roles/install_dependencies_and_basic_configuration/tasks/main.yml
  sheetstorm-deployment/roles/postgres_backup/tasks/main.yml
Labels: deployment, feature

#383 Chore add type annotations in exports.py file
  employees/common/exports.py
  mypy.ini
Labels: chore

#384 Bugfix missing work hours during updating reports
  employees/forms.py
Labels: bug

#385 Bugfix change names in UI
  employees/templates/employees/author_report_list.html
  managers/templates/managers/projects_list.html
  users/templates/base.html
Labels: bug

#379 Fill context on invalid form response
  employees/views.py
Labels: bug

#389 Bugfix disable mounting additional disk on the local virtual machine
  sheetstorm-deployment/roles/postgres_backup/tasks/main.yml
Labels: bug, deployment

#391 Chore change type annotation from Decimal to timedelta
  employees/common/exports.py
  employees/models.py
Labels: chore

#390 Bugfix add auto assigning manager if he create project
  managers/forms.py
  managers/views.py
Labels: bug

#406 Update release-notes for `v0.7.4` tag
  RELEASE-NOTES.md
Labels: chore

#407 Feature Add NotificationsApp
  notifications/__init__.py
  notifications/apps.py
  notifications/urls.py
  sheetstorm/settings/base.py
  sheetstorm/urls.py
Labels: feature

#388 Add information about deployment process
  sheetstorm-deployment/README.md
Labels: chore, deployment

#417 Bugfix work hours display in report update
  employees/templates/employees/project_report_detail.html
  employees/templates/employees/report_detail.html
  employees/templates/employees/report_list.html
  users/templates/base.html
Labels: bug

#418 Remove `django-allauth` leftovers
  requirements.lock
  requirements.txt
  sheetstorm/settings/base.py
Labels: chore

#419 Stats at the bottom of report list should involve reports from last 3…
  utils/mixins.py
  utils/tests/test_mixins.py
Labels: bug

#423 Bugfix OpenOffice does not display full description
  employees/common/constants.py
  employees/common/exports.py
Labels: bug, priority high

#427 Bugfix weekends should be skipped in reports date suggestion
  employees/tests/test_views.py
  employees/views.py
Labels: bug

#428 Fix urls namespace and add reverse to missing usages in tests
  employees/tests/test_unit_custom_mixins.py
  employees/tests/test_views.py
  sheetstorm/urls.py
  users/tests/test_views.py
Labels: bug

#451 Change CustomUser's manager to enable migration making
  users/migrations/0006_auto_20190722_1131.py
  users/models.py
Labels: bug, priority high

#453 Change project's property from `terminated` to `suspended`
  managers/migrations/0005_auto_20190722_1104.py
  managers/models.py
  managers/templates/managers/project_detail.html
  managers/templates/managers/projects_list.html
  managers/tests/test_unit_model.py
  managers/tests/test_views.py
  users/management/commands/load_initial_data.py
  users/views.py
Labels: chore, priority high, refactor

#446 Bugfix custom report list
  employees/tests/test_views.py
  employees/views.py
Labels: bug, priority high

#440 Bugfix total hours in csv in project reports
  employees/common/constants.py
  employees/common/exports.py
  employees/tests/test_unit_export_data.py
  employees/views.py
Labels: bug, priority medium

#439 Feature add lines separators in columns
  employees/common/constants.py
  employees/common/exports.py
Labels: feature, priority medium

#392 Chore add system checks
  common/constants.py
  sheetstorm/apps.py
  sheetstorm/settings/base.py
  sheetstorm/system_check.py
  utils/tests/test_system_check.py
Labels: chore, priority medium

#450 Bugfix add task activities to Report in initial data
  load_initial_data.sh
  users/management/commands/load_initial_data.py
Labels: bug, priority low

#448 Bugfix set active actual url
  users/templates/base.html
Labels: bug, priority medium

#455 Change name from 'My Reports' to 'Reports'
  users/templates/base.html
Labels: bug, priority low

#458 Chore add virtual environments packages checks
  check-environment-packages.sh
  full-check.sh
Labels: chore

#465 Bugfix add freeze_time decorator to work percentage time mixin tests
  utils/tests/test_mixins.py
Labels: bug

#463 Chore Improvement to check-environment-packages script
  check-environment-packages.sh
Labels: chore

#464 Chore clear migrations in all applications
  employees/migrations/0001_initial.py
  employees/migrations/0002_auto_20190730_1515.py
  employees/migrations/0003_auto_20190530_1210.py
  employees/migrations/0004_auto_20190530_1211.py
  employees/migrations/0005_auto_20190530_1211.py
  employees/migrations/0006_auto_20190725_0850.py
  managers/migrations/0001_initial.py
  managers/migrations/0002_auto_20190730_1515.py
  managers/migrations/0003_auto_20190506_0733.py
  managers/migrations/0004_auto_20190709_1325.py
  managers/migrations/0005_auto_20190722_1104.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20190527_1153.py
  users/migrations/0003_auto_20190614_0842.py
  users/migrations/0004_auto_20190701_0653.py
  users/migrations/0005_auto_20190703_1737.py
  users/migrations/0006_auto_20190722_1131.py
Labels: chore
