Repository Code-Poets/sheetstorm, pull requests merged in 2019-06, with the labels that each got.

#265 Show day numer as non-zero padded decimal
  employees/tests/test_unit_report_viewset.py
Labels: bug

#270 Add a playbook that creates compute instance for sheetstorm
  sheetstorm-deployment/create-compute-instance-for-sheetstorm.yml
  sheetstorm-deployment/roles/reserve_static_ip/tasks/main.yml
Labels: deployment

#276 Feature group days and add daily hours to xlsx export
  employees/common/constants.py
  employees/common/exports.py
  employees/tests/test_unit_export_data.py
Labels: feature

#275 Bugfix - Add discard button to admin report detail
  employees/templates/employees/admin_report_detail.html
Labels: bug

#277 Bugfix - Add validation to stop_date field in project
  managers/commons/constants.py
  managers/models.py
  managers/tests/test_unit_model.py
Labels: bug

#286 Disable code inspection on `sheetstorm-deployment` directory
  find-files-to-refactor.sh
  lint.sh
  manage.py
Labels: bug

#279 Bugfix delete button to send it as a post method
  employees/static/employees/scripts/basic_popup_window.js
  employees/templates/employees/report_detail.html
Labels: bug

#280 Bugfix add return button in project report list
  employees/templates/employees/project_report_list.html
Labels: bug

#294 Chore update release notes for version v0.5.0
  RELEASE-NOTES.md
Labels: chore

#305 Pass markdown_description property to template
  employees/templates/employees/author_report_list.html
Labels: bug

#319 Bugfix manager can't edit his own reports in projects where he is not manager
  employees/tests/test_views.py
  employees/views.py
  utils/mixins.py
  utils/tests/test_mixins.py
Labels: bug, priorityy high

#296 Chore remove django rest framework
  common/convert.py
  employees/forms.py
  employees/serializers.py
  employees/templates/employees/author_report_list.html
  employees/templates/employees/project_report_list.html
  employees/tests/test_unit_report_serializer.py
  employees/tests/test_unit_report_viewset.py
  employees/tests/test_views.py
  employees/urls.py
  employees/views.py
  managers/templates/managers/project_detail.html
  managers/templates/managers/project_form.html
  managers/templates/managers/projects_list.html
  requirements.lock
  requirements.txt
  sheetstorm/settings/base.py
  sheetstorm/urls.py
  users/permissions.py
  users/serializers.py
  users/templates/accounts/change_password.html
  users/templates/accounts/password_reset_complete.html
  users/templates/base.html
  users/tests/test_unit_customuser_serializer.py
  users/tests/test_unit_customuser_signals.py
  users/tests/test_unit_users_permissions.py
  users/tests/test_views.py
  users/urls.py
  users/views.py
Labels: change to Django views, chore, priorityy high

#323 Chore delete the django middleware that is responsible for sending 404 http error to the sentry environment
  sheetstorm/settings/base.py
Labels: chore, security

#324 Feature add cron job that automatically renew Let's Encrypt Certificate
  sheetstorm-deployment/configure-sheetstorm-server.yml
Labels: deployment, feature

#328 Fix for incorrect html tag
  managers/templates/managers/project_detail.html
Labels: bug

#329 Unify test naming by removing "that" from tests name schema
  employees/tests/test_unit_custom_forms.py
  employees/tests/test_unit_export_data.py
  employees/tests/test_unit_report_model.py
  employees/tests/test_unit_templatetags.py
  managers/tests/test_unit_model.py
  users/tests/test_unit_customuser_model.py
  users/tests/test_unit_template_tags.py
  users/tests/test_unit_validators.py
  users/tests/test_views.py
  utils/tests/test_access_permissions.py
  utils/tests/test_mixins.py
Labels: chore

#332 Add possibility to export monthly reports for every user
  employees/templates/employees/report_list.html
  employees/templatetags/data_display_filters.py
  employees/tests/test_unit_templatetags.py
  employees/views.py
  utils/tests/test_access_permissions.py
Labels: feature

#334 Bugfix make hyperlink highlighted
  employees/static/employees/style.css
  employees/templates/employees/report_list.html
Labels: UX, bug, priority medium

#335 Bugfix hide toggle button
  users/static/users/center_style.css
Labels: UX, bug, priority high

#283 Feature rebuild register interface
  users/common/constants.py
  users/forms.py
  users/static/users/center_style.css
  users/templates/signup.html
  users/urls.py
Labels: feature

#338 Bugfix add a missing file that allows you to reset database in the virtual machine
  sheetstorm-deployment/sheetstorm-vm/files/reset-db.sh
Labels: bug

#339 Feature add encryption to postgres backups
  sheetstorm-deployment/consts.yml
  sheetstorm-deployment/roles/postgres_backup/tasks/main.yml
  sheetstorm-deployment/roles/postgres_backup/templates/pg_backup.sh.j2
Labels: deployment, feature, security

#340 Add security for exporting own reports
  employees/tests/test_unit_export_data.py
  employees/views.py
Labels: bug, priority high

#341 Update release notes for v0.6.0 tag
  RELEASE-NOTES.md
Labels: chore

#346 Feature add day name to reports
  employees/static/employees/style.css
  employees/templates/employees/author_report_list.html
  employees/templates/employees/report_list.html
Labels: feature

#347 Bugfix move directives that configure modsecurity nginx module to another place in the nginx config files
  sheetstorm-deployment/roles/configure_nginx/templates/maintenance-remote.j2
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
Labels: bug

#353 Feature add nginx endpoint that allows downloading encrypted postgres backups
  sheetstorm-deployment/configure-sheetstorm-server.yml
  sheetstorm-deployment/consts.yml
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-local.j2
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
  sheetstorm-deployment/roles/postgres_backup/templates/pg_backup.sh.j2
Labels: deployment, feature, security

#354 Bugfix MultipleObjectsReturned exception when manager wants to edit his reports
  employees/tests/test_views.py
  utils/mixins.py
Labels: bug, priority high

#355 Chore update release notes for `v0.7.0` tag
  RELEASE-NOTES.md
Labels: chore

#344 Chore unify display errors in form
  users/templates/registration/login.html
Labels: chore, priority medium, refactor
