Repository Code-Poets/sheetstorm, pull requests merged in 2019-10, with the labels that each got.

#542 Add linebreaks filter to reports description
  employees/templates/employees/partial/display_reports/reports_in_date_for_author.html
Labels: UX, bug

#543 Bugfix redirect admin to his own report edition
  employees/templates/employees/partial/display_reports/reports_in_date_for_author.html
  employees/tests/test_views.py
Labels: bug

#518 Chore rename task activities to activities
  employees/admin.py
  employees/common/constants.py
  employees/common/exports.py
  employees/common/strings.py
  employees/factories.py
  employees/fixtures/activities.yaml
  employees/forms.py
  employees/migrations/0004_auto_20191022_0948.py
  employees/models.py
  employees/static/employees/scripts/load_activities_for_project.js
  employees/static/employees/style.css
  employees/templates/employees/partial/create_and_join_dialog.html
  employees/templates/employees/partial/display_reports/display_user_reports.html
  employees/templates/employees/partial/display_reports/reports_in_date_for_author.html
  employees/templates/employees/partial/task_activity_list.html
  employees/templates/employees/project_report_list.html
  employees/templates/employees/report_detail.html
  employees/tests/test_unit_export_data.py
  employees/tests/test_unit_report_model.py
  employees/tests/test_views.py
  employees/urls.py
  employees/views.py
  load_initial_data.sh
  managers/models.py
  managers/static/managers/style.css
  managers/templates/managers/partials/display_projects.html
  managers/templates/managers/project_activities.html
  managers/templates/managers/project_detail.html
  managers/tests/test_unit_project_signals.py
  managers/tests/test_views.py
  managers/urls.py
  managers/views.py
  sheetstorm-deployment/sheetstorm-vm/configure-sheetstorm-vm.yml
  users/management/commands/load_initial_data.py
  users/models.py
Labels: chore
