Repository Code-Poets/sheetstorm, pull requests merged in 2020-05, with the labels that each got.

#555 Feature delete whitelisting admin panel
  sheetstorm-deployment/roles/configure_nginx/templates/sheetstorm-remote.j2
Labels: feature

#554 Chore update all project dependecies
  Pipfile.lock
  check-environment-packages.sh
  employees/tests/test_unit_custom_mixins.py
  employees/tests/test_unit_export_data.py
  managers/models.py
  pylintrc
  pytest.ini
  sheetstorm/apps.py
  users/tests/test_views.py
  users/tokens.py
  users/views.py
  utils/mixins.py
Labels: chore

#553 Bugfix inactive users are displayed in app
  employees/tests/test_views.py
  managers/forms.py
  managers/tests/test_views.py
  managers/views.py
  users/forms.py
  users/models.py
  users/tests/test_unit_customuser_model.py
  users/tests/test_unit_customuser_signals.py
  users/tests/test_views.py
  users/views.py
Labels: bug

#552 Feature improve monthly hours stats
  employees/common/strings.py
  employees/static/employees/style.css
  employees/templates/employees/partial/projects_work_percentage.html
  employees/tests/test_unit_report_model.py
  users/models.py
  utils/mixins.py
  utils/tests/test_mixins.py
Labels: feature

#541 Feature rebuild notifications interface
  users/static/users/center_style.css
  users/static/users/style.css
  users/templates/user_notifications_list.html
Labels: UX, feature, priority high

#515 Feature improve sidebar responsiveness
  users/static/users/center_style.css
  users/static/users/images/code-poets-logo.png
  users/static/users/images/full-code-poets-logo.png
  users/static/users/images/grey/ico-01.png
  users/static/users/images/grey/ico-02.png
  users/static/users/images/grey/ico-03.png
  users/static/users/images/grey/ico-04.png
  users/static/users/images/grey/ico-05.png
  users/static/users/images/grey/ico-23.png
  users/static/users/images/grey/notifications.png
  users/static/users/images/ico-32.png
  users/static/users/images/logo-login.png
  users/static/users/images/logo.png
  users/static/users/images/name-login.png
  users/static/users/images/white/iko-01.png
  users/static/users/images/white/iko-02.png
  users/static/users/images/white/iko-03.png
  users/static/users/images/white/iko-04.png
  users/static/users/images/white/iko-05.png
  users/static/users/images/white/notifications.png
  users/static/users/scripts/float_menu.js
  users/templates/base.html
  users/templates/registration/login.html
  users/templates/signup.html
Labels: feature

#513 Feature refactor project create view
  managers/forms.py
  managers/static/managers/images/ico-11.png
  managers/static/managers/style.css
  managers/templates/managers/partials/delete-project-modal.html
  managers/templates/managers/partials/project_create_form.html
  managers/templates/managers/project_form.html
  managers/views.py
Labels: UX, feature, priority high

#557 Change ordering in employees' list
  users/templates/users_list.html
  users/tests/test_views.py
  users/views.py
Labels: feature
