Repository Code-Poets/sheetstorm, pull requests merged in 2020-06, with the labels that each got.

#559 Bugfix incorrect hours stats
  employees/tests/test_unit_report_model.py
  employees/tests/test_views.py
  employees/views.py
  users/models.py
  users/tests/test_unit_customuser_model.py
  users/views.py
  utils/mixins.py
  utils/tests/test_mixins.py
Labels: bug, priority high

#561 Chore update project dependencies
  Pipfile.lock
Labels: chore

#562 Chore update release notes
  RELEASE-NOTES.md
Labels: chore

#563 Bugfix default date on report creation
  RELEASE-NOTES.md
  employees/tests/test_views.py
  employees/views.py
Labels: bug
